version: '3.8'

services:
  api-gateway:
    build: ./api-gateway
    ports:
      - "8000:8000"
    environment:
      - APPOINTMENT_SERVICE_URL=http://appointment-service:8004
    depends_on:
      - auth-service
      - patient-service
      - appointment-service

  auth-service:
    build: ./services/auth-service
    ports:
      - "8001:8001"

  patient-service:
    build: ./services/patient-service
    ports:
      - "8002:8002"

  appointment-service:
    build: ./services/appointment-service
    ports:
      - "8004:8004"

  # ... more services will be added
