apiVersion: v1
kind: Secret
metadata:
  name: medisync-secrets
  labels:
    app: medisync
type: Opaque
stringData:
  # --- MongoDB Atlas Connection Strings ---
  MONGODB_URL_AUTH: "mongodb+srv://MediLink:Medi123@medilink.kfrfcd8.mongodb.net/auth?retryWrites=true&w=majority&appName=MediLink"
  MONGODB_URL_PATIENTS: "mongodb+srv://MediLink:Medi123@medilink.kfrfcd8.mongodb.net/patients?retryWrites=true&w=majority&appName=MediLink"
  MONGODB_URL_APPOINTMENTS: "mongodb+srv://MediLink:Medi123@medilink.kfrfcd8.mongodb.net/appointments?retryWrites=true&w=majority&appName=MediLink"
  MONGODB_URL_DOCTORS: "mongodb+srv://MediLink:Medi123@medilink.kfrfcd8.mongodb.net/doctors?retryWrites=true&w=majority&appName=MediLink"
  MONGODB_URL_NOTIFICATIONS: "mongodb://MediLink:Medi123@ac-bgidhrn-shard-00-00.kfrfcd8.mongodb.net:27017,ac-bgidhrn-shard-00-01.kfrfcd8.mongodb.net:27017,ac-bgidhrn-shard-00-02.kfrfcd8.mongodb.net:27017/notifications?tls=true&authSource=admin&retryWrites=true&w=majority"
  MONGODB_URL_PAYMENTS: "mongodb+srv://MediLink:Medi123@medilink.kfrfcd8.mongodb.net/payments?retryWrites=true&w=majority&appName=MediLink"
  MONGODB_URL_SYMPTOM: "mongodb+srv://MediLink:Medi123@medilink.kfrfcd8.mongodb.net/symptom_checker?retryWrites=true&w=majority&appName=MediLink"
  MONGODB_URL_TELEMEDICINE: "mongodb+srv://MediLink:Medi123@medilink.kfrfcd8.mongodb.net/telemedicine?retryWrites=true&w=majority&appName=MediLink"

  # --- Authentication ---
  JWT_SECRET: "shanuka"
  ADMIN_EMAIL: "admin@medisync.com"
  ADMIN_PASSWORD: "Admin32"
  
  # --- API Keys (External Services) ---
  STRIPE_SECRET_KEY: "REPLACE_WITH_ENV"
  CLERK_SECRET_KEY: "REPLACE_WITH_YOUR_ACTUAL_CLERK_SECRET_KEY"
  
  # --- Email Credentials ---
  EMAIL_USER: "a0159c001@smtp-brevo.com"
  EMAIL_PASSWORD: "bskp0sYZyhvUSnM"
  
  # --- Internal Secrets ---
  NOTIFICATION_INTERNAL_SECRET: "medilink-local-notification-secret-change-me"
  
  # --- Media Storage ---
  CLOUDINARY_URL: "cloudinary://515479316863945:Fl4MtNpG5wuMnflikgNrq04ipN8@dg46muu2y"
  CLOUDINARY_NAME: "dg46muu2y"
  CLOUDINARY_API_KEY: "515479316863945"
  CLOUDINARY_SECRET_KEY: "Fl4MtNpG5wuMnflikgNrq04ipN8"
