apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: patient-reports-pvc
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: patient-service
  labels:
    app: patient-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: patient-service
  template:
    metadata:
      labels:
        app: patient-service
    spec:
      containers:
      - name: patient-service
        image: medisync-patient-service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8002
        env:
        - name: PORT
          valueFrom:
            configMapKeyRef:
              name: medisync-config
              key: PORT_PATIENT
        - name: MONGODB_URL
          valueFrom:
            secretKeyRef:
              name: medisync-secrets
              key: MONGODB_URL_PATIENTS
        - name: PATIENT_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: medisync-config
              key: PATIENT_DB_NAME
        - name: ADMIN_DB_NAME
          valueFrom:
            configMapKeyRef:
              name: medisync-config
              key: ADMIN_DB_NAME
        - name: NOTIFICATION_SERVICE_URL
          valueFrom:
            configMapKeyRef:
              name: medisync-config
              key: NOTIFICATION_SERVICE_URL
        volumeMounts:
        - name: reports-storage
          mountPath: /app/src/uploads/reports
      volumes:
      - name: reports-storage
        persistentVolumeClaim:
          claimName: patient-reports-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: patient-service
spec:
  selector:
    app: patient-service
  ports:
  - protocol: TCP
    port: 8002
    targetPort: 8002
  type: ClusterIP
